config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :orders, only: %i[index create]
  end
  resources :users, only: [:show]
  resources :cards, only: %i[new create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください', on: :create

  with_options presence: true do
    validates :nickname
    validates :birthday
  end
  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'には全角文字を使用してください' } do
    validates :first_name
    validates :last_name
  end
  with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: 'には全角カナ文字を使用してください' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  has_many :items
  has_many :orders
  has_one :card, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[show]

  def show
    show_card
  end

  private

  def show_card
    @user = current_user
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      customer = Payjp::Customer.retrieve(card.customer_token)
      @card = customer.cards.first
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/second-header"%>
<div class='user-show-main'>
  <div class='user-show-wrap'>
    <div class='user-show-header'>
      <h1 class='user-show-header-text'>
        会員情報
      </h1>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
        <label class="user-show-text">ニックネーム</label>
      </div>
      <p class="user-show-value"><%= @user.nickname %></p>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
        <label class="user-show-text">メールアドレス</label>
      </div>
      <p class="user-show-value"><%= @user.email %></p>
    </div>
    <div class='user-show-btn'>
      <br>
      <%= link_to "登録情報変更",edit_user_registration_path(current_user) , class:"user-show-grey-btn"%>
    </div>
    <% if @card.present? %>
    <div class='user-show-header'>
      <h1 class='user-show-header-text'>
        カード情報
      </h1>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
          <label class="user-show-text">カード番号</label>
      </div>
      <%= "**** **** **** " + @card[:last4].to_s %>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
          <label class="user-show-text">有効期限</label>
      </div>
      <%= @card[:exp_month] %>
      /
      <%= @card[:exp_year] %>
    </div>
    <div class='user-show-btn'>
      <%= link_to "カード削除", card_path(current_user.id),method: :delete, class:"user-show-grey-btn" %>
    </div>
    <% else %>
    <div class='user-show-btn'>
      <%= link_to "カード登録", new_card_path, class:"user-show-red-btn" %>
    </div>
    <% end %>
    <div class='user-show-header'>
      <h1 class='user-show-header-text'>
        本人情報
      </h1>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
        <label class="user-show-text">お名前(全角)</label>
      </div>
      <p class="user-show-value"><%= @user.last_name %> <%= @user.first_name %></p>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
        <label class="user-show-text">お名前カナ(全角)</label>
      </div>
      <p class="user-show-value"><%= @user.last_name_kana %> <%= @user.first_name_kana %></p>
    </div>
    <div class="user-show-group">
      <div class='user-show-text-wrap'>
        <label class="user-show-text">生年月日</label>
      </div>
      <p class="user-show-value"><%= @user.birthday.to_s[0, 4] %>年
                                 <%= @user.birthday.to_s[5, 2] %>月
                                 <%= @user.birthday.to_s[8, 2] %>日</p>
    </div>
    <div class='user-show-btn'>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"user-show-grey-btn"%>
    </div>
    <div class='user-show-btn'>
      <%= link_to "商品一覧へ戻る", root_path, class:"user-show-red-btn"%>
    </div>
  </div>
</div>
<%= render "shared/second-footer"%>