config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :orders, only: %i[index create]
  end
  resources :users, only: [:show]
  resources :cards, only: %i[new create destroy]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  attr_accessor :card_token

  validates :card_token, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def new
    binding.pry
    session[:previous_url] = request.referer
  end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(
      description: 'test',
      card: params[:card_token]
    )
    card = Card.new(
      card_token: params[:card_token],
      customer_token: customer.id,
      user_id: current_user.id
    )
    if card.save
      redirect_to session[:previous_url]
    else
      render :new
    end
  end

  def destroy
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV['PAYJP_SECRET_KEY']
      customer = Payjp::Customer.retrieve(card.customer_token)
      customer.delete
      card.delete
    end
    redirect_to user_path(current_user)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<%= render "shared/second-header"%>
<div class= "transaction-contents">
  <div class= "transaction-main">
    <%= form_with url: cards_path, id: 'charge-form', class: 'card-form',local: true do |f| %>
      <div class='credit-card-form'>
        <h1 class='info-input-haedline'>
        クレジットカード情報入力
        </h1>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">カード情報</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :number, class:"input-default", id:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
          <div class='available-card'>
            <%= image_tag 'card-visa.gif', class: 'card-logo'%>
            <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
            <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
            <%= image_tag 'card-amex.gif', class: 'card-logo'%>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">有効期限</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='input-expiration-date-wrap'>
            <%= f.text_area :exp_month, class:"input-expiration-date", id:"exp_month", placeholder:"例)3" %>
            <p>月</p>
            <%= f.text_area :exp_year, class:"input-expiration-date", id:"exp_year", placeholder:"例)23" %>
            <p>年</p>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">セキュリティコード</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :cvc, class:"input-default", id:"cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
          <div class='buy-btn'>
            <%= f.submit "登録" ,class:"buy-red-btn",id:"card-button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>